image: node:20

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - app/frontend/node_modules

stages:
  - install
  - build
  - test

install:
  stage: install
  script:
    - cd app/frontend
    - npm ci

build:
  stage: build
  script:
    - cd app/frontend
    - npm ci
    - npm run build
  artifacts:
    when: always
    paths:
      - app/frontend/dist

test:
  stage: test
  script:
    - cd app/frontend
    - npm ci
    - npm test || echo "No test script"

deploy:
  stage: deploy
  script:
    - npm install -g vercel
    - vercel --token $VERCEL_TOKEN --prod --confirm --cwd app/frontend
  only:
    - main    
