image: node:20

stages:
  - install
  - build
  - test

variables:
  NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/.npm"

cache:
  key:
    files:
      - app/frontend/package-lock.json
  paths:
    - .npm/
  policy: pull-push

install:
  stage: install
  script:
    - cd app/frontend
    - npm ci --prefer-offline --no-audit
  artifacts:
    expire_in: 1 hour
    paths:
      - app/frontend/node_modules/

build:
  stage: build
  needs: ["install"]
  script:
    - cd app/frontend
    - npm run build
  artifacts:
    when: always
    paths:
      - app/frontend/dist

test:
  stage: test
  needs: ["install"]
  script:
    - cd app/frontend
    - npm test
