version: "3.8"
services:
  backend:
    build: ./app/backend
    ports:
      - "4000:4000"
    container_name: pokemon-backend
    environment:
      - PORT=4000

  frontend:
    build:
      context: ./app/frontend
      args:
        - VITE_BACKEND_URL=http://localhost:4000
    ports:
      - "8080:80"
    container_name: pokemon-frontend
    depends_on:
      - backend
